import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { ThemeProvider } from '@/components/ThemeProvider';
import './globals.css';
import Header from '@/components/header/Header';
import Footer from '@/components/footer/Footer';
import StoreProvider from './StoreProvider';
import { Toaster } from '@/components/ui/sonner';
import { GlobalReqProvider } from './sea-battle/context/GlobalRequestContext';
import { SoundProvider } from '@/lib/sounds/SoundContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <GlobalReqProvider>
              <Header />
              <SoundProvider>
                <main className="w-full flex justify-center items-center flex-wrap pt-30">
                  <div className="container max-w-7xl mx-auto flex justify-center items-center flex-wrap px-3">
                    {children}
                    <Toaster />
                  </div>
                </main>
              </SoundProvider>
              <Footer />
            </GlobalReqProvider>
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
